on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      # Only lint once, it's not going to be different per platform
      - name: Lint
        if: matrix.platform == 'ubuntu-latest'
        run: npm run lint

      - name: Build
        run: npm run build:client

      - name: Build macOS Image
        if: matrix.platform == 'macos-latest'
        run: npm run build:mac

      - name: Build Windows Portable
        if: matrix.platform == 'windows-latest'
        run: npm run build:win

      - name: Build for Linux (deb, rpm, appImage)
        if: matrix.platform == 'ubuntu-latest'
        run: npm run build:linux

      # Test after building once per platform
      - name: Test
        run: npm run test

      # Build additional only after tests pass
      # These change data from previous builds, so must be built separate

      - name: Build Windows Installer
        if: matrix.platform == 'windows-latest'
        run: npm run build:nsis

      - name: Build for Snapcraft
        if: matrix.platform == 'ubuntu-latest'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          SNAPCRAFT_BUILD_ENVIRONMENT: host
        run: |
          sudo snap install snapcraft --classic
          npm run build:snap
