on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build:client
          npm run build:electron

      - name: Build for macOS
        if: matrix.platform == 'macos-latest'
        run: npm run build:mac

      - name: Build for Windows
        if: matrix.platform == 'windows-latest'
        run: npm run build:win

      - name: Build for Linux
        if: matrix.platform == 'ubuntu-latest'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          SNAPCRAFT_BUILD_ENVIRONMENT: host
        run: |
          npm run build:linux
          sudo snap install snapcraft --classic
          npm run build:snap
